name: poc_angulardart_subapps

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: 5.0.0-alpha+4
  angular_components: 0.9.0-alpha+3
  angular_router: 2.0.0-alpha+4
  build: ^0.12.0

dev_dependencies:
  build_runner: '^0.7.0'
  build_web_compilers: '^0.2.1'
  build_test: '^0.10.0'
  angular_test: '2.0.0-alpha+2'
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: any
  shelf: any
  shelf_proxy: any

dependency_overrides:
  analyzer: ^0.31.0-alpha

transformers:
- angular:
    entry_points:
    - web/main.dart
    - web/users/main.dart
    - web/groups/main.dart
    - test/**_test.dart
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions:
      - --trust-type-annotations
      - --trust-primitives
      - --dump-info
    minify: true
    environment:
      requirejs: 'false'
- test/pub_serve:
    $include: test/**_test.dart
