name: shared_lib

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_forms: ^2.0.0-alpha
  angular_router: ^2.0.0-alpha
  angular_components: ^0.9.0-alpha
  build: ^0.12.0

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.8
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^0.12.35
  shelf: any
  shelf_proxy: any